"""SAMPLE META Doc
{
    "_id" : ObjectId("68b9960a41c48bfb65fb9041"),
    "ds_id" : "IITD_v1",
    "db_info" : {
        "name" : "IITD.v1",
        "desc" : "\n\n        Description of the IITD Iris Image Database version 1.0\n=======================================================\n\nThis iris image database mainly consists of the iris images collected from the students and staff at IIT Delhi, India. This database has been acquired in\nthe Biometrics Research Laboratory during January - July 2007 using JIRIS, JPC1000, digital CMOS camera. The acquired images were saved in bitmap format.\nThe database of 2240 images is acquired from 224 different users and made available freely to the researchers. All the subjects in the database are in the\nage group 14-55 years comprising of 176 males and 48 females. The resolution of these images is 320 x 240 pixels and all these images were acquired in the\nindoor environment. All the images in the database were acquired from the volunteers who were not paid or provided any honorarium. The images were acquired\nusing an automated program that requires users to present their eyes in a sequence until ten images are registered.\n\nOrganization of Database\n========================\nThe acquired database is saved in 224 folders, each corresponding to 224 subjects. Majority of images were acquired from the left eyes while the rest images\nwere acquired from right eye. Now the database has a label 'L' or 'R' which designates left or right eye. There are 1288 images from 224 subject that are from\nleft eyes while the rest images from 211 subjects are from right eyes.Except folders 1-13, 27, 55 and 65 all other folders have five left and 5 right eye \nimages. (**appended on 20-04-2016**).\n\nUsage of Database\n========================\nThis database is only available for research and noncommercial purposes. Commercial distribution or any act related to commercial use of this database is strictly\nprohibited. Kindly acknowledge all the publicly available publications/work employing this database with the following acknowledgment:\n\n\"Portions of the work tested on the IITD Iris Database version 1.0\"\nA citation to \"IIT Delhi Iris Database version 1.0, http://web.iitd.ac.in/~biometrics/Database_Iris.htm\n\nRelated Publication:\n====================\nAjay Kumar and Arun Passi, \"Comparison and combination of iris matchers for reliable personal identification,\" Proc. CVPR 2008, Anchorage, Alaska, pp. 21-27 Jun. 2008\n\nContact Information:\n====================\nAjay Kumar\nBiometrics Research Laboratory\nIndian Institute of Technology Delhi\nNew Delhi, India\nE-mail: ajaykr@ieee.org\n\n        IITD Iris Database Version 1.0\nThe IIT Delhi IrisDatabase (Version 1.0) is publicly available for academic use only. While every effort has been made to ensure accuracy of this database, we cannot accept responsibility for errors or omissions. The academic use of this database is free of charge. Any commercial distribution or act related to the commercial usage of this database is strictly prohibited. The distribution of this database to any parties that have not read and agreed to the terms and conditions of usage is strictly prohibited. Neither IIT Delhi, nor any third parties who may provide information to us for the dissemination purpose, shall have any responsibility for or be liable in respect of the content or the accuracy of the provided information, or for any errors or omissions therein. The IIT Delhi reserves the right to revise, amend, alter or delete the information provided herein at any time, but shall not be responsible for or liable in respect of any such revisions, amendments, alterations or deletions. Any publication using this database must reference to this website: http://web.iitd.ac.in/~biometrics/Database_Iris.htm, and this paper: A. Kumar and A. Passi, Comparison and combination of iris matchers for reliable personal identification, Proc. CVPR, Anchorage, pp. 21-27, Jun. 2008. The images available in this database can only be published or presented in research papers or at research conferences and cannot be used for any commercial purpose.\n\n        ",
        "capture_device" : "JIRIS, JPC1000, digital CMOS camera",
        "environment" : "indoor",
        "type" : "NIR",
        "notes" : "",
        "periocular" : false
    },
    "tags" : [
        "orig",
        "norm_def"
    ],
    "tags_info" : {
        "orig" : {
            "info" : "original images",
            "num_images" : NumberInt(2240),
            "num_people" : NumberInt(224),
            "num_eyes" : NumberInt(435),
            "num_eyes_per_person" : {
                "1" : [
                    "1",
                    "10",
                    "11",
                    "12",
                    "13",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6",
                    "7",
                    "8",
                    "9"
                ],
                "2" : [
                    "100",
                    "101",
                    "102",
                    "103",
                    "104",
                    "105",
                    "106",
                    "107",
                    "108",
                    "109",
                    "110",
                    "111",
                    "112",
                    "113",
                    "114",
                    "115",
                    "116",
                    "117",
                    "118",
                    "119",
                    "120",
                    "121",
                    "122",
                    "123",
                    "124",
                    "125",
                    "126",
                    "127",
                    "128",
                    "129",
                    "130",
                    "131",
                    "132",
                    "133",
                    "134",
                    "135",
                    "136",
                    "137",
                    "138",
                    "139",
                    "14",
                    "140",
                    "141",
                    "142",
                    "143",
                    "144",
                    "145",
                    "146",
                    "147",
                    "148",
                    "149",
                    "15",
                    "150",
                    "151",
                    "152",
                    "153",
                    "154",
                    "155",
                    "156",
                    "157",
                    "158",
                    "159",
                    "16",
                    "160",
                    "161",
                    "162",
                    "163",
                    "164",
                    "165",
                    "166",
                    "167",
                    "168",
                    "169",
                    "17",
                    "170",
                    "171",
                    "172",
                    "173",
                    "174",
                    "175",
                    "176",
                    "177",
                    "178",
                    "179",
                    "18",
                    "180",
                    "181",
                    "182",
                    "183",
                    "184",
                    "185",
                    "186",
                    "187",
                    "188",
                    "189",
                    "19",
                    "190",
                    "191",
                    "192",
                    "193",
                    "194",
                    "195",
                    "196",
                    "197",
                    "198",
                    "199",
                    "20",
                    "200",
                    "201",
                    "202",
                    "203",
                    "204",
                    "205",
                    "206",
                    "207",
                    "208",
                    "209",
                    "21",
                    "210",
                    "211",
                    "212",
                    "213",
                    "214",
                    "215",
                    "216",
                    "217",
                    "218",
                    "219",
                    "22",
                    "220",
                    "221",
                    "222",
                    "223",
                    "224",
                    "23",
                    "24",
                    "25",
                    "26",
                    "27",
                    "28",
                    "29",
                    "30",
                    "31",
                    "32",
                    "33",
                    "34",
                    "35",
                    "36",
                    "37",
                    "38",
                    "39",
                    "40",
                    "41",
                    "42",
                    "43",
                    "44",
                    "45",
                    "46",
                    "47",
                    "48",
                    "49",
                    "50",
                    "51",
                    "52",
                    "53",
                    "54",
                    "55",
                    "56",
                    "57",
                    "58",
                    "59",
                    "60",
                    "61",
                    "62",
                    "63",
                    "64",
                    "65",
                    "66",
                    "67",
                    "68",
                    "69",
                    "70",
                    "71",
                    "72",
                    "73",
                    "74",
                    "75",
                    "76",
                    "77",
                    "78",
                    "79",
                    "80",
                    "81",
                    "82",
                    "83",
                    "84",
                    "85",
                    "86",
                    "87",
                    "88",
                    "89",
                    "90",
                    "91",
                    "92",
                    "93",
                    "94",
                    "95",
                    "96",
                    "97",
                    "98",
                    "99"
                ]
            },
            "num_eyes_per_person_count" : {
                "1" : NumberInt(13),
                "2" : NumberInt(211)
            },
            "num_samples_per_eye" : {
                "5" : [
                    "100_L",
                    "100_R",
                    "101_L",
                    "101_R",
                    "102_L",
                    "102_R",
                    "103_L",
                    "103_R",
                    "104_L",
                    "104_R",
                    "105_L",
                    "105_R",
                    "106_L",
                    "106_R",
                    "107_L",
                    "107_R",
                    "108_L",
                    "108_R",
                    "109_L",
                    "109_R",
                    "110_L",
                    "110_R",
                    "111_L",
                    "111_R",
                    "112_L",
                    "112_R",
                    "113_L",
                    "113_R",
                    "114_L",
                    "114_R",
                    "115_L",
                    "115_R",
                    "116_L",
                    "116_R",
                    "117_L",
                    "117_R",
                    "118_L",
                    "118_R",
                    "119_L",
                    "119_R",
                    "120_L",
                    "120_R",
                    "121_L",
                    "121_R",
                    "122_L",
                    "122_R",
                    "123_L",
                    "123_R",
                    "124_L",
                    "124_R",
                    "125_L",
                    "125_R",
                    "126_L",
                    "126_R",
                    "127_L",
                    "127_R",
                    "128_L",
                    "128_R",
                    "129_L",
                    "129_R",
                    "130_L",
                    "130_R",
                    "131_L",
                    "131_R",
                    "132_L",
                    "132_R",
                    "133_L",
                    "133_R",
                    "134_L",
                    "134_R",
                    "135_L",
                    "135_R",
                    "136_L",
                    "136_R",
                    "137_L",
                    "137_R",
                    "138_L",
                    "138_R",
                    "139_L",
                    "139_R",
                    "140_L",
                    "140_R",
                    "141_L",
                    "141_R",
                    "142_L",
                    "142_R",
                    "143_L",
                    "143_R",
                    "144_L",
                    "144_R",
                    "145_L",
                    "145_R",
                    "146_L",
                    "146_R",
                    "147_L",
                    "147_R",
                    "148_L",
                    "148_R",
                    "149_L",
                    "149_R",
                    "14_L",
                    "14_R",
                    "150_L",
                    "150_R",
                    "151_L",
                    "151_R",
                    "152_L",
                    "152_R",
                    "153_L",
                    "153_R",
                    "154_L",
                    "154_R",
                    "155_L",
                    "155_R",
                    "156_L",
                    "156_R",
                    "157_L",
                    "157_R",
                    "158_L",
                    "158_R",
                    "159_L",
                    "159_R",
                    "15_L",
                    "15_R",
                    "160_L",
                    "160_R",
                    "161_L",
                    "161_R",
                    "162_L",
                    "162_R",
                    "163_L",
                    "163_R",
                    "164_L",
                    "164_R",
                    "165_L",
                    "165_R",
                    "166_L",
                    "166_R",
                    "167_L",
                    "167_R",
                    "168_L",
                    "168_R",
                    "169_L",
                    "169_R",
                    "16_L",
                    "16_R",
                    "170_L",
                    "170_R",
                    "171_L",
                    "171_R",
                    "172_L",
                    "172_R",
                    "173_L",
                    "173_R",
                    "174_L",
                    "174_R",
                    "175_L",
                    "175_R",
                    "176_L",
                    "176_R",
                    "177_L",
                    "177_R",
                    "178_L",
                    "178_R",
                    "179_L",
                    "179_R",
                    "17_L",
                    "17_R",
                    "180_L",
                    "180_R",
                    "181_L",
                    "181_R",
                    "182_L",
                    "182_R",
                    "183_L",
                    "183_R",
                    "184_L",
                    "184_R",
                    "185_L",
                    "185_R",
                    "186_L",
                    "186_R",
                    "187_L",
                    "187_R",
                    "188_L",
                    "188_R",
                    "189_L",
                    "189_R",
                    "18_L",
                    "18_R",
                    "190_L",
                    "190_R",
                    "191_L",
                    "191_R",
                    "192_L",
                    "192_R",
                    "193_L",
                    "193_R",
                    "194_L",
                    "194_R",
                    "195_L",
                    "195_R",
                    "196_L",
                    "196_R",
                    "197_L",
                    "197_R",
                    "198_L",
                    "198_R",
                    "199_L",
                    "199_R",
                    "19_L",
                    "19_R",
                    "200_L",
                    "200_R",
                    "201_L",
                    "201_R",
                    "202_L",
                    "202_R",
                    "203_L",
                    "203_R",
                    "204_L",
                    "204_R",
                    "205_L",
                    "205_R",
                    "206_L",
                    "206_R",
                    "207_L",
                    "207_R",
                    "208_L",
                    "208_R",
                    "209_L",
                    "209_R",
                    "20_L",
                    "20_R",
                    "210_L",
                    "210_R",
                    "211_L",
                    "211_R",
                    "212_L",
                    "212_R",
                    "213_L",
                    "213_R",
                    "214_L",
                    "214_R",
                    "215_L",
                    "215_R",
                    "216_L",
                    "216_R",
                    "217_L",
                    "217_R",
                    "218_L",
                    "218_R",
                    "219_L",
                    "219_R",
                    "21_L",
                    "21_R",
                    "220_L",
                    "220_R",
                    "221_L",
                    "221_R",
                    "222_L",
                    "222_R",
                    "223_L",
                    "223_R",
                    "224_L",
                    "224_R",
                    "22_L",
                    "22_R",
                    "23_L",
                    "23_R",
                    "24_L",
                    "24_R",
                    "25_L",
                    "25_R",
                    "26_L",
                    "26_R",
                    "28_L",
                    "28_R",
                    "29_L",
                    "29_R",
                    "30_L",
                    "30_R",
                    "31_L",
                    "31_R",
                    "32_L",
                    "32_R",
                    "33_L",
                    "33_R",
                    "34_L",
                    "34_R",
                    "35_L",
                    "35_R",
                    "36_L",
                    "36_R",
                    "37_L",
                    "37_R",
                    "38_L",
                    "38_R",
                    "39_L",
                    "39_R",
                    "40_L",
                    "40_R",
                    "41_L",
                    "41_R",
                    "42_L",
                    "42_R",
                    "43_L",
                    "43_R",
                    "44_L",
                    "44_R",
                    "45_L",
                    "45_R",
                    "46_L",
                    "46_R",
                    "47_L",
                    "47_R",
                    "48_L",
                    "48_R",
                    "49_L",
                    "49_R",
                    "50_L",
                    "50_R",
                    "51_L",
                    "51_R",
                    "52_L",
                    "52_R",
                    "53_L",
                    "53_R",
                    "54_L",
                    "54_R",
                    "56_L",
                    "56_R",
                    "57_L",
                    "57_R",
                    "58_L",
                    "58_R",
                    "59_L",
                    "59_R",
                    "60_L",
                    "60_R",
                    "61_L",
                    "61_R",
                    "62_L",
                    "62_R",
                    "63_L",
                    "63_R",
                    "64_L",
                    "64_R",
                    "66_L",
                    "66_R",
                    "67_L",
                    "67_R",
                    "68_L",
                    "68_R",
                    "69_L",
                    "69_R",
                    "70_L",
                    "70_R",
                    "71_L",
                    "71_R",
                    "72_L",
                    "72_R",
                    "73_L",
                    "73_R",
                    "74_L",
                    "74_R",
                    "75_L",
                    "75_R",
                    "76_L",
                    "76_R",
                    "77_L",
                    "77_R",
                    "78_L",
                    "78_R",
                    "79_L",
                    "79_R",
                    "80_L",
                    "80_R",
                    "81_L",
                    "81_R",
                    "82_L",
                    "82_R",
                    "83_L",
                    "83_R",
                    "84_L",
                    "84_R",
                    "85_L",
                    "85_R",
                    "86_L",
                    "86_R",
                    "87_L",
                    "87_R",
                    "88_L",
                    "88_R",
                    "89_L",
                    "89_R",
                    "90_L",
                    "90_R",
                    "91_L",
                    "91_R",
                    "92_L",
                    "92_R",
                    "93_L",
                    "93_R",
                    "94_L",
                    "94_R",
                    "95_L",
                    "95_R",
                    "96_L",
                    "96_R",
                    "97_L",
                    "97_R",
                    "98_L",
                    "98_R",
                    "99_L",
                    "99_R"
                ],
                "10" : [
                    "10_L",
                    "11_L",
                    "12_L",
                    "13_L",
                    "1_L",
                    "2_L",
                    "3_L",
                    "4_L",
                    "5_L",
                    "6_L",
                    "7_L",
                    "8_L",
                    "9_L"
                ],
                "6" : [
                    "27_L",
                    "55_L",
                    "65_L"
                ],
                "4" : [
                    "27_R",
                    "55_R",
                    "65_R"
                ]
            },
            "num_samples_per_eye_count" : {
                "5" : NumberInt(416),
                "10" : NumberInt(13),
                "6" : NumberInt(3),
                "4" : NumberInt(3)
            },
            "num_sessions" : [
                "1"
            ],
            "img_specs" : {
                "ext" : ".bmp",
                "res" : "320x240",
                "width" : NumberInt(320),
                "height" : NumberInt(240)
            },
            "orig_base_" : "/home/nishkal/datasets/iris_datasets/IITD/IITD V1/IITD Database"
        },
        "norm_def" : {
            "name" : "Normalized images default using Daugman's rubber sheet model",
            "orig_base_" : "/home/nishkal/datasets/iris_datasets/IITD/IITD V1/Normalized_Images"
        }
    },
    "paths" : {
        "base_" : "/home/nishkal/datasets/iris_db/IITD_v1"
    },
    "injested_at" : ISODate("2025-09-08T14:17:58.701+0000")
}
"""

DB = {
    "db_base_": str,  # path to the database in the iris_db folder, eg: /home/<user>/datasets/iris_db/
    "db_name": str,  # eg: 'iris_db'
    "meta_coll": str,  # eg: 'meta'
}
META = [
    {
        "ds_id": str,  # indexed(unique), eg: 'iitd_v1'
        "doc": str,  # gdoc link
        "img_tags": list,  # list of tags eg: ['orig', 'norm_def']
        "injested_at": str,  # ISO timestamp of insertion
        "{img_tag}": {
            "info": str,  # eg: 'original images'
            "stats": {
                "num_images": int,  # total number of images
                "num_people": int,  # total number of people
                "num_eyes": int,  # total number of eyes
                "num_eyes_per_person": {
                    "{eye_count}": list,  # {'{eye_count}':list[{person_id},...]}
                },
                "num_eyes_per_person_count": {
                    "{eye_count}": int,  # {'{eye_count}': Count of people with {eye_count} eyes}
                },
                "num_samples_per_eye": {
                    "{sample_count}": list,  # {'{sample_count}':list[{eye_id},...]}
                },
                "num_samples_per_eye_count": {
                    "{sample_count}": int,  # {'{sample_count}': Count of eyes with {sample_count} samples}
                },
                "num_sessions": list,  # list of session ids eg: ['1', '2']
            },
            "img_specs": {
                "ext": str,  # eg: '.bmp'
                "width": int,  # eg: 320
                "height": int,  # eg: 240
            },
            "git": str,  # OPTIONAL eg: link to github code for extraction
            "old_base_": str,  # path to original database for this tag
        },
        "fv_tags": list,  # list of feature vector tags eg: ['iris_code', 'deep_fv']
        "{fv_tag}": {
            "info": str,  # eg: 'Iris code using Daugman's method'
            "dim": int,  # eg: 2048 (dimension of the feature vector) (may be different for each file)
            "type": str,  # eg: 'binary' or 'float'
            "notes": str,  # any notes
        },
        # 'base_':str, # Inherited:<f"{db_base}/{ds_id}"> -> path to the database in the iris_db folder
    },
]

""" DS sample doc
{
    "ds_id" : "IITD_v1",
    "person_id" : "1",
    "eye" : "L",
    "eye_id" : "1_L",
    "sample_id" : "1",
    "person_sample_id" : "1",
    "session_id" : "1",
    "image_id" : "1_L_1",
    "tags" : [
        "orig",
        "norm_def"
    ],
    #"img_specs" : { # may be inherited from meta data if constant in all images
    #    "ext" : ".bmp",
    #    "width" : NumberInt(320),
    #    "height" : NumberInt(240)
    #},

    "injested_at" : ISODate("2025-09-04T13:21:58.424+0000")
}
"""
DS = [
    {
        "ds_id": str,  # eg: 'iitd_v1'
        "person_id": str,  # indexed, eg: '1'
        "eye": str,  # eg: 'L' or 'R'
        "eye_id": str,  # indexed, eg: '1_L' (f'{person_id}_{eye}')
        "sample_id": str,  # eg: '1' (sample number for this eye)
        "sample_id_person": str,  # eg: '1' (f'{sample_id}*{eye_count}+{eye_index}')
        "session_id": str,  # eg: '1' (session number)
        "image_id": str,  # indexed(unique), eg: '1_L_1' (f'{eye_id}_{sample_id}')
        "img_tags": list,  # list of tags eg: ['orig', 'norm_def']
        "{img_tag}": {
            # 'img_specs':{  # may be inherited from meta data if constant in all images
            # 'ext':str, # eg: '.bmp'
            # 'width':int, # eg: 320
            # 'height':int # eg: 240
            # }
            "orig_rel_path": str,  # path to original image,
            "injested_at": str,  # ISO timestamp of insertion
        },
        "fv_tags": list,  # list of feature vector tags eg: ['iris_code', 'deep_fv']
        # store features here if needed
        "{fv_tag}": {"fv": list},  # eg: [0.1, 0.2, ...]
    }
]
