meta = {
    "_id": "68c907b8dd89bc27175b609b",
    "ds_id": "CASIA_v1",
    "name": "CASIA-IrisV1",
    "doc": "https://docs.google.com/document/d/1N_ninklrJYcEyG0EUuSx_KmBeHvnOYrtBTEw1yMZXNM/edit?tab=t.6abuy1phj6an",
    "img_tags": ["orig"],
    "orig": {
        "info": "Original images",
        "old_base_": "~/datasets/iris_datasets/CASIA/V1/CASIA-IrisV1/CASIA-IrisV1/CASIA Iris Image Database (version 1.0)",
        "img_specs": {"ext": ".bmp", "width": 320, "height": 280},
    },
}

meta_long = {
    "_id": "68c907b8dd89bc27175b609b",
    "ds_id": "CASIA_v1",
    "name": "CASIA-IrisV1",
    "doc": "https://docs.google.com/document/d/1N_ninklrJYcEyG0EUuSx_KmBeHvnOYrtBTEw1yMZXNM/edit?tab=t.6abuy1phj6an",
    "img_tags": ["orig"],
    "orig": {
        "info": "Original images",
        "old_base_": "~/datasets/iris_datasets/CASIA/V1/CASIA-IrisV1/CASIA-IrisV1/CASIA Iris Image Database (version 1.0)",
        "img_specs": {"ext": ".bmp", "width": 320, "height": 280},
        "stats": {
            "num_images": 756,
            "num_people": 108,
            "num_eyes": 108,
            "num_eyes_per_person": {
                "1": [
                    "1",
                    "10",
                    "100",
                    "101",
                    "102",
                    "103",
                    "104",
                    "105",
                    "106",
                    "107",
                    "108",
                    "11",
                    "12",
                    "13",
                    "14",
                    "15",
                    "16",
                    "17",
                    "18",
                    "19",
                    "2",
                    "20",
                    "21",
                    "22",
                    "23",
                    "24",
                    "25",
                    "26",
                    "27",
                    "28",
                    "29",
                    "3",
                    "30",
                    "31",
                    "32",
                    "33",
                    "34",
                    "35",
                    "36",
                    "37",
                    "38",
                    "39",
                    "4",
                    "40",
                    "41",
                    "42",
                    "43",
                    "44",
                    "45",
                    "46",
                    "47",
                    "48",
                    "49",
                    "5",
                    "50",
                    "51",
                    "52",
                    "53",
                    "54",
                    "55",
                    "56",
                    "57",
                    "58",
                    "59",
                    "6",
                    "60",
                    "61",
                    "62",
                    "63",
                    "64",
                    "65",
                    "66",
                    "67",
                    "68",
                    "69",
                    "7",
                    "70",
                    "71",
                    "72",
                    "73",
                    "74",
                    "75",
                    "76",
                    "77",
                    "78",
                    "79",
                    "8",
                    "80",
                    "81",
                    "82",
                    "83",
                    "84",
                    "85",
                    "86",
                    "87",
                    "88",
                    "89",
                    "9",
                    "90",
                    "91",
                    "92",
                    "93",
                    "94",
                    "95",
                    "96",
                    "97",
                    "98",
                    "99",
                ]
            },
            "num_eyes_per_person_count": {"1": 108},
            "num_samples_per_eye": {
                "7": [
                    "100_L",
                    "101_L",
                    "102_L",
                    "103_L",
                    "104_L",
                    "105_L",
                    "106_L",
                    "107_L",
                    "108_L",
                    "10_L",
                    "11_L",
                    "12_L",
                    "13_L",
                    "14_L",
                    "15_L",
                    "16_L",
                    "17_L",
                    "18_L",
                    "19_L",
                    "1_L",
                    "20_L",
                    "21_L",
                    "22_L",
                    "23_L",
                    "24_L",
                    "25_L",
                    "26_L",
                    "27_L",
                    "28_L",
                    "29_L",
                    "2_L",
                    "30_L",
                    "31_L",
                    "32_L",
                    "33_L",
                    "34_L",
                    "35_L",
                    "36_L",
                    "37_L",
                    "38_L",
                    "39_L",
                    "3_L",
                    "40_L",
                    "41_L",
                    "42_L",
                    "43_L",
                    "44_L",
                    "45_L",
                    "46_L",
                    "47_L",
                    "48_L",
                    "49_L",
                    "4_L",
                    "50_L",
                    "51_L",
                    "52_L",
                    "53_L",
                    "54_L",
                    "55_L",
                    "56_L",
                    "57_L",
                    "58_L",
                    "59_L",
                    "5_L",
                    "60_L",
                    "61_L",
                    "62_L",
                    "63_L",
                    "64_L",
                    "65_L",
                    "66_L",
                    "67_L",
                    "68_L",
                    "69_L",
                    "6_L",
                    "70_L",
                    "71_L",
                    "72_L",
                    "73_L",
                    "74_L",
                    "75_L",
                    "76_L",
                    "77_L",
                    "78_L",
                    "79_L",
                    "7_L",
                    "80_L",
                    "81_L",
                    "82_L",
                    "83_L",
                    "84_L",
                    "85_L",
                    "86_L",
                    "87_L",
                    "88_L",
                    "89_L",
                    "8_L",
                    "90_L",
                    "91_L",
                    "92_L",
                    "93_L",
                    "94_L",
                    "95_L",
                    "96_L",
                    "97_L",
                    "98_L",
                    "99_L",
                    "9_L",
                ]
            },
            "num_samples_per_eye_count": {"7": 108},
            "num_sessions": ["1", "2"],
        },
    },
}
